#! /bin/sh
feh --bg-scale /home/cahoner/Imágenes/fondo.jpg &
pkill picom
picom -f --daemon --config $HOME/.config/picom/picom.conf &

~/.config/polybar/colorblocks/launch.sh


vmware-user-suid-wrapper

pgrep -x sxhkd > /dev/null || sxhkd &



bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^9' state=tilted #follow=off
bspc rule -a Google-chrome desktop='^2' state=tilted #follow=off
bspc rule -a Firefox-esr desktop='^4' state=tilted follow=off
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a burp-StartBurp desktop='^3' state=tilted focus=off
# Autorun
kitty --session ~/.config/kitty/kitty-startup.session
